In [1]:
import os, uuid
import azure
from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
import pandas as pd
import numpy as np
import openpyxl
from azure.storage.blob import BlobServiceClient
import time

In [2]:
STORAGEACCOUNTURL= "https://bdousncvbaddmv01sta.blob.core.windows.net"
STORAGEACCOUNTKEY= "JhbiDWfvxlthZngR4WkZDaaxhE/QMWj8bIXvdNH8MTvHYxNoSRq88UifxDawqeMlVpYuR3vpokQi52Ek1Ccqsw=="
CONTAINERNAME= "newcontainer"

def download_csv_from_cloud_storage(LOCALFILENAME, BLOBNAME, HEADER):
    """
    Function to load csv file from Azure Blob Storage into Pandas Dataframe.

        Inputs: {'LOCALFILENAME': path to local temporary destination (string), 'BLOBNAME': name of storage object we would like to call (string), 'HEADER': number of rows to be considered for header (int)},
        Outputs: {'df': Dataframe from input Blob Object}
    """
    # Download File from blob and save as Temp File
    t1=time.time()
    blob_service_client_instance = BlobServiceClient(account_url=STORAGEACCOUNTURL, credential=STORAGEACCOUNTKEY)
    blob_client_instance = blob_service_client_instance.get_blob_client(CONTAINERNAME, BLOBNAME, snapshot=None)
    with open(LOCALFILENAME, "wb") as my_blob:
        blob_data = blob_client_instance.download_blob()
        blob_data.readinto(my_blob)
    t2=time.time()
    print(("It takes %s seconds to download "+BLOBNAME) % (t2 - t1))


    # Read In Data Frame
    df = pd.read_csv(LOCALFILENAME, header=HEADER)
    # Remove Temporary File
    os.remove(LOCALFILENAME)
    return df

def download_pipe_from_cloud_storage(LOCALFILENAME, BLOBNAME, HEADER):
    """
    Function to load csv file from Azure Blob Storage into Pandas Dataframe.

        Inputs: {'LOCALFILENAME': path to local temporary destination (string), 'BLOBNAME': name of storage object we would like to call (string), 'HEADER': number of rows to be considered for header (int)},
        Outputs: {'df': Dataframe from input Blob Object}
    """
    
    # Download File from blob and save as Temp File
    t1=time.time()
    blob_service_client_instance = BlobServiceClient(account_url=STORAGEACCOUNTURL, credential=STORAGEACCOUNTKEY)
    blob_client_instance = blob_service_client_instance.get_blob_client(CONTAINERNAME, BLOBNAME, snapshot=None)
    with open(LOCALFILENAME, "wb") as my_blob:
        blob_data = blob_client_instance.download_blob()
        blob_data.readinto(my_blob)
    t2=time.time()
    print(("It takes %s seconds to download "+BLOBNAME) % (t2 - t1))


    # Read In Data Frame
    df = pd.read_csv(LOCALFILENAME, header=HEADER, sep = '|')
    # Remove Temporary File
    os.remove(LOCALFILENAME)
    return df

def download_excel_from_cloud_storage(LOCALFILENAME, BLOBNAME, HEADER, SHEETNAME):
    """
    Function to load csv file from Azure Blob Storage into Pandas Dataframe.

        Inputs: {'LOCALFILENAME': path to local temporary destination (string), 'BLOBNAME': name of storage object we would like to call (string), 'HEADER': number of rows to be considered for header (int), 'SHEETNAME': name of tab in Excel workbook which data resides},
        Outputs: {'df': Dataframe from input Blob Object}
    """
    # Download File from blob and save as Temp File
    t1=time.time()
    blob_service_client_instance = BlobServiceClient(account_url=STORAGEACCOUNTURL, credential=STORAGEACCOUNTKEY)
    blob_client_instance = blob_service_client_instance.get_blob_client(CONTAINERNAME, BLOBNAME, snapshot=None)
    with open(LOCALFILENAME, "wb") as my_blob:
        blob_data = blob_client_instance.download_blob()
        blob_data.readinto(my_blob)
    t2=time.time()
    print(("It takes %s seconds to download "+BLOBNAME) % (t2 - t1))

    # Read In Data Frame
    df = pd.read_excel(LOCALFILENAME, header=HEADER, sheet_name=SHEETNAME)
    # Remove Temporary File
    os.remove(LOCALFILENAME)
    return df

In [84]:
census_2022 = download_csv_from_cloud_storage('temp_df', "CensusFlatFile2022.csv", None)
census_2022.columns = census_2022.columns+1
census_2022

It takes 7.104017019271851 seconds to download CensusFlatFile2022.csv

<ipython-input-84-b0bcc5594f51>:1: DtypeWarning: Columns (15,16,17,18,21) have mixed types.Specify dtype option on import or set low_memory=False.
  census_2022 = download_csv_from_cloud_storage('temp_df', "CensusFlatFile2022.csv", None)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212
0,2022,33860,1,1,20100,0,T,N,D,NaN,68115.0,54250.0,103.79,75500,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1775.0,555.0,693.0,963.0,978.0,399.0,22.48,1775.0,76.0,1699.0,1608.0,1376.0,213.0,5.0,8.0,0.0,6.0,91.0,84.0,14.0,34.0,13.0,9.0,9.0,0.0,227.0,39.0,21.0,9.0,15.0,12.0,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1775.0,1653.0,1389.0,213.0,5.0,8.0,3.0,35.0,122.0,114.0,19.0,34.0,14.0,9.0,32.0,0.0,232.0,39.0,22.0,12.0,67.0,14.0,NaN,NaN,NaN,NaN,NaN,1941.0,1941.0,693.0,381.0,71.0,310.0,312.0,58.0,254.0,382.0,0.0,9.0,0.0,689.0,605.0,13.0,71.0,32.0,28.0,44.0,4.0,7.0,17.0,0.0,36.0,0.0,295.0,295.0,217.0,120.0,63.0,57.0,46.0,44.0,4.0,3.0,0.0,78.0,44.0,44.0,0.0,29.0,25.0,4.0,5.0,0.0,1941.0,978.0,61.0,97.0,50.0,21.0,43.0,24.0,0.0,47.0,31.0,74.0,80.0,51.0,44.0,123.0,37.0,40.0,34.0,11.0,9.0,33.0,8.0,32.0,28.0,208.0,21.0,114.0,185.0,95.0,200.0,155.0,121.0,963.0,37.0,55.0,62.0,32.0,16.0,27.0,0.0,60.0,17.0,82.0,117.0,14.0,56.0,117.0,74.0,5.0,18.0,8.0,25.0,54.0,8.0,28.0,51.0,154.0,32.0,103.0,216.0,70.0,196.0,192.0,174.0,98.0,152.0,112.0,53.0,59.0,51.0,0.0,107.0,48.0,156.0,197.0,65.0,100.0,240.0,111.0,45.0,52.0,19.0,34.0,87.0,16.0,60.0,79.0,362.0,53.0,217.0,401.0,165.0,396.0,347.0,295.0,229.0,154.0,0.0,32.0,38.0,37.0,38.0,1843.0,317.0,315.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1231.0,1223.0,3.0,3.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,295.0,291.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1309.0,635.0,0.0,0.0,31.0,33.0,5.0,0.0,15.0,5.0,258.0,11.0,57.0,54.0,108.0,22.0,24.0,12.0,674.0,0.0,0.0,0.0,3.0,14.0,57.0,21.0,3.0,185.0,23.0,146.0,63.0,94.0,47.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1558.0,749.0,523.0,0.0,510.0,508.0,15.0,226.0,809.0,329.0,0.0,308.0,326.0,3.0,480.0,693.0,25.0,47.0,66.0,35.0,8.0,6.0,26.0,15.0,16.0,98.0,111.0,70.0,22.0,33.0,77.0,38.0,60388.0,551.0,21.0,33.0,48.0,33.0,8.0,6.0,26.0,15.0,16.0,33.0,106.0,54.0,19.0,33.0,62.0,38.0,93.0,4.0,2.0,18.0,2.0,0.0,0.0,0.0,0.0,0.0,28.0,5.0,16.0,3.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,24.0,0.0,520.0,21.0,33.0,48.0,33.0,8.0,6.0,26.0,15.0,16.0,33.0,106.0,47.0,19.0,33.0,38.0,38.0,63352.0,54330.0,0.0,0.0,0.0,0.0,0.0,0.0,61810.0,693.0,510.0,183.0,693.0,81.0,612.0,693.0,140.0,553.0,693.0,280.0,413.0,693.0,20.0,673.0,693.0,0.0,693.0,693.0,151.0,542.0,693.0,94.0,599.0,555.0,11.0,26.0,28.0,15.0,4.0,6.0,11.0,6.0,11.0,96.0,105.0,70.0,22.0,33.0,73.0,38.0,70699.0,439.0,11.0,14.0,28.0,15.0,4.0,6.0,11.0,6.0,11.0,31.0,100.0,54.0,19.0,33.0,58.0,38.0,67.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,5.0,16.0,3.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,24.0,0.0,408.0,11.0,14.0,28.0,15.0,4.0,6.0,11.0,6.0,11.0,31.0,100.0,47.0,19.0,33.0,34.0,38.0,72463.0,75104.0,0.0,0.0,0.0,0.0,0.0,0.0,71324.0,17429.0,87536,91474,93134,155241,86629,1941.0,265.0,36.0,0.0,13.0,44.0,155.0,17.0,0.0,1676.0,62.0,10.0,182.0,68.0,1076.0,123.0,155.0,13.65,555.0,77.0,20.0,20.0,0.0,15.0,5.0,0.0,57.0,14.0,14.0,0.0,0.0,14.0,0.0,43.0,31.0,0.0,15.0,16.0,12.0,478.0,413.0,139.0,5.0,49.0,85.0,274.0,65.0,14.0,8.0,2.0,0.0,6.0,6.0,51.0,5.0,0.0,0.0,5.0,46.0,693.0,98.0,77.0,20.0,0.0,15.0,5.0,0.0,57.0,14.0,0.0,0.0,14.0,0.0,43.0,0.0,26.0,5.0,12.0,21.0,15.0,0.0,7.0,3.0,5.0,6.0,0.0,0.0,6.0,0.0,595.0,478.0,413.0,0.0,160.0,182.0,71.0,65.0,14.0,0.0,6.0,6.0,2.0,51.0,0.0,0.0,16.0,35.0,117.0,56.0,17.0,0.0,0.0,39.0,61.0,0.0,0.0,32.0,29.0,710.0,NaN,NaN,710.0,693.0,17.0,693.0,507.0,186.0,17.0,0.0,0.0,0.0,0.0,0.0,17.0,710.0,594.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,88.0,0.0,710.0,0.0,693.0,507.0,436.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0,0.0,507.0,0.0,186.0,141.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,17.0,0.0,186.0,0.0,551.0,462.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,61.0,0.0,551.0,0.0,93.0,78.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,93.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,12.0,0.0,31.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,0.0,520.0,431.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,61.0,0.0,520.0,0.0,710.0,5.0,25.0,85.0,101.0,146.0,82.0,93.0,84.0,50.0,39.0,1980.0,40.0,693.0,507.0,1.0,69.0,28.0,222.0,122.0,65.0,186.0,0.0,111.0,55.0,17.0,0.0,3.0,710.0,710.0,0.0,693.0,507.0,507.0,0.0,186.0,186.0,0.0,186.0,149.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,33.0,5.0,11.0,15.0,0.0,0.0,28.0,7.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,820.0,186.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,49.0,0.0,0.0,0.0,3.0,0.0,32.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0,43.0,4.0,0.0,0.0,0.0,0.0,0.0,37.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,507.0,278.0,250.0,28.0,0.0,10.0,18.0,0.0,229.0,507.0,34.0,1.0,21.0,0.0,0.0,3.0,0.0,47.0,3.0,0.0,28.0,39.0,19.0,37.0,18.0,75.0,18.0,63.0,20.0,34.0,30.0,15.0,0.0,2.0,0.0,0.0,151200.0
1,2022,33860,1,1,20200,0,T,N,D,NaN,68115.0,54250.0,73.60,75500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2055.0,359.0,573.0,747.0,1010.0,1221.0,59.42,2055.0,43.0,2012.0,1952.0,834.0,1098.0,2.0,12.0,1.0,5.0,60.0,57.0,24.0,10.0,3.0,0.0,8.0,4.0,1122.0,12.0,15.0,1.0,13.0,15.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2055.0,1984.0,842.0,1104.0,2.0,12.0,4.0,20.0,71.0,64.0,24.0,10.0,3.0,0.0,15.0,4.0,1128.0,12.0,15.0,4.0,35.0,19.0,NaN,NaN,NaN,NaN,NaN,1757.0,1545.0,573.0,230.0,92.0,138.0,343.0,99.0,244.0,202.0,0.0,37.0,0.0,439.0,385.0,51.0,3.0,148.0,20.0,42.0,0.0,0.0,47.0,0.0,37.0,212.0,284.0,284.0,199.0,112.0,32.0,80.0,25.0,34.0,0.0,28.0,0.0,85.0,16.0,16.0,0.0,64.0,64.0,0.0,5.0,0.0,1757.0,1010.0,81.0,77.0,22.0,52.0,16.0,0.0,5.0,35.0,194.0,108.0,71.0,34.0,93.0,67.0,46.0,26.0,7.0,12.0,17.0,21.0,26.0,0.0,0.0,180.0,52.0,56.0,373.0,127.0,139.0,83.0,76.0,747.0,25.0,20.0,7.0,41.0,4.0,16.0,27.0,16.0,65.0,37.0,46.0,70.0,32.0,36.0,54.0,7.0,36.0,30.0,63.0,44.0,33.0,6.0,32.0,52.0,41.0,63.0,148.0,102.0,97.0,244.0,208.0,106.0,97.0,29.0,93.0,20.0,16.0,32.0,51.0,259.0,145.0,117.0,104.0,125.0,103.0,100.0,33.0,43.0,42.0,80.0,65.0,59.0,6.0,32.0,232.0,93.0,119.0,521.0,229.0,236.0,327.0,284.0,223.0,84.0,9.0,9.0,44.0,31.0,36.0,1651.0,219.0,219.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1148.0,1142.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,284.0,279.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1313.0,722.0,7.0,0.0,0.0,9.0,25.0,27.0,13.0,18.0,388.0,21.0,93.0,13.0,103.0,5.0,0.0,0.0,591.0,0.0,0.0,9.0,0.0,4.0,5.0,5.0,17.0,273.0,32.0,87.0,59.0,66.0,19.0,15.0,0.0,142.0,142.0,142.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1450.0,787.0,406.0,12.0,379.0,377.0,17.0,381.0,663.0,323.0,0.0,305.0,311.0,12.0,340.0,573.0,50.0,12.0,51.0,10.0,16.0,65.0,9.0,33.0,59.0,79.0,32.0,90.0,22.0,31.0,14.0,0.0,49144.0,213.0,0.0,11.0,0.0,3.0,1.0,6.0,0.0,12.0,6.0,54.0,4.0,72.0,22.0,15.0,7.0,0.0,346.0,50.0,1.0,51.0,7.0,15.0,58.0,9.0,21.0,53.0,25.0,15.0,18.0,0.0,16.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,213.0,0.0,11.0,0.0,3.0,1.0,6.0,0.0,12.0,6.0,54.0,4.0,72.0,22.0,15.0,7.0,0.0,80446.0,32112.0,0.0,0.0,0.0,0.0,69000.0,0.0,80446.0,573.0,457.0,116.0,573.0,35.0,538.0,573.0,53.0,520.0,573.0,254.0,319.0,573.0,56.0,517.0,573.0,6.0,567.0,573.0,144.0,429.0,573.0,52.0,521.0,359.0,16.0,5.0,35.0,10.0,11.0,2.0,4.0,41.0,53.0,53.0,25.0,61.0,12.0,17.0,14.0,0.0,50133.0,127.0,0.0,4.0,0.0,3.0,1.0,0.0,0.0,12.0,0.0,28.0,4.0,43.0,12.0,13.0,7.0,0.0,222.0,16.0,1.0,35.0,7.0,10.0,2.0,4.0,29.0,53.0,25.0,11.0,18.0,0.0,4.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127.0,0.0,4.0,0.0,3.0,1.0,0.0,0.0,12.0,0.0,28.0,4.0,43.0,12.0,13.0,7.0,0.0,83750.0,47604.0,0.0,0.0,0.0,0.0,0.0,0.0,83750.0,31653.0,60821,83385,47612,0,83385,1511.0,257.0,12.0,0.0,57.0,43.0,109.0,12.0,24.0,1254.0,82.0,5.0,32.0,60.0,827.0,175.0,73.0,17.01,359.0,56.0,36.0,35.0,0.0,0.0,35.0,1.0,20.0,12.0,0.0,0.0,0.0,0.0,12.0,8.0,8.0,4.0,4.0,0.0,0.0,303.0,166.0,72.0,18.0,26.0,28.0,94.0,137.0,35.0,5.0,0.0,5.0,0.0,30.0,102.0,29.0,12.0,17.0,0.0,73.0,573.0,111.0,56.0,36.0,0.0,35.0,0.0,1.0,20.0,12.0,0.0,7.0,5.0,0.0,8.0,0.0,8.0,0.0,0.0,55.0,31.0,4.0,0.0,20.0,7.0,24.0,1.0,0.0,2.0,21.0,462.0,303.0,166.0,0.0,73.0,57.0,36.0,137.0,35.0,0.0,6.0,24.0,5.0,102.0,0.0,17.0,15.0,70.0,159.0,83.0,0.0,45.0,29.0,9.0,76.0,0.0,5.0,28.0,43.0,720.0,NaN,NaN,720.0,573.0,147.0,573.0,392.0,181.0,147.0,32.0,0.0,17.0,0.0,0.0,98.0,720.0,645.0,4.0,28.0,35.0,0.0,0.0,0.0,3.0,5.0,0.0,717.0,3.0,573.0,392.0,390.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,392.0,0.0,181.0,124.0,4.0,28.0,19.0,0.0,0.0,0.0,3.0,3.0,0.0,178.0,3.0,213.0,184.0,4.0,18.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,213.0,0.0,346.0,317.0,0.0,10.0,11.0,0.0,0.0,0.0,3.0,5.0,0.0,343.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,13.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,213.0,184.0,4.0,18.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,213.0,0.0,720.0,0.0,10.0,64.0,70.0,62.0,196.0,143.0,15.0,58.0,102.0,1972.0,48.0,573.0,392.0,0.0,41.0,32.0,76.0,86.0,157.0,181.0,14.0,52.0,67.0,14.0,13.0,21.0,720.0,705.0,15.0,573.0,392.0,392.0,0.0,181.0,181.0,0.0,181.0,181.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,3.0,0.0,21.0,0.0,7.0,4.0,39.0,14.0,18.0,14.0,14.0,37.0,0.0,0.0,0.0,0.0,0.0,846.0,181.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,49.0,0.0,0.0,0.0,3.0,0.0,0.0,46.0,0.0,11.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,4.0,17.0,0.0,44.0,4.0,7.0,9.0,20.0,4.0,0.0,0.0,0.0,35.0,29.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,392.0,170.0,143.0,27.0,0.0,0.0,27.0,0.0,222.0,392.0,2.0,5.0,5.0,0.0,0.0,15.0,0.0,2.0,71.0,13.0,37.0,81.0,19.0,33.0,33.0,44.0,17.0,6.0,4.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,85700.0

In [85]:
census_2022_dd = download_excel_from_cloud_storage('temp_df', "FFIEC_Census_File_Definitions_26AUG22.xlsx", 0, "Data Dictionary")
census_2022_dd.Index = census_2022_dd.Index.fillna(0).astype(int)
census_2022_dd = census_2022_dd.set_index('Index')
census_2022_dd

It takes 0.05399608612060547 seconds to download FFIEC_Census_File_Definitions_26AUG22.xlsx

,Description,Max Length,Data Type,Data Source,Source Field
Index,,,,,
0,Other - Board calculated,NaN,NaN,NaN,NaN
1,Key field. HMDA/CRA collection year,4.0,AN,Other,NaN
2,Key field. MSA/MD Code,5.0,AN,Other,NaN
3,Key field. FIPS state code,2.0,AN,Other,NaN
4,Key field. FIPS county code,3.0,AN,Other,NaN
...,...,...,...,...,...
1210,"Total owner-occupied units $1,500,000 to $1,99...",8.0,N,ACS,B25075_026
1211,"Total owner-occupied units $2,000,000 or more",8.0,N,ACS,B25075_027
0,NaN,NaN,NaN,NaN,NaN
0,Median value (in dollars) for all owner-occupi...,NaN,NaN,NaN,NaN
1212,Median value in dollars for all owner-occupied...,8.0,N,ACS,B25077_001

In [86]:
new_col_list = []
for col in census_2022.columns:
    new_col_list.append(census_2022_dd.loc[col].Description)

In [87]:
census_2022.columns = new_col_list
census_2022.columns = census_2022.columns.str.lstrip('Key field. ')

### UPDATE: Need to get this showing as the 11 digit Census tract. We can convert to integer if needed, but safer to leave as full 11 digit string.
# Concatenate 'FIPS state code' (length: 2), 'FIPS county code' (length: 3), and 'Census tract' (length: 6)

census_2022['census_tract_merge'] = (census_2022['FIPS state code'].astype(str).str.pad(width=2, side='left', fillchar='0') + 
                                    census_2022['FIPS county code'].astype(str).str.pad(width=3, side='left', fillchar='0') + 
                                    census_2022['Census tract. Implied decimal point.'].astype(str).str.pad(width=6, side='left', fillchar='0'))
census_2022

,HMDA/CRA collection year,MSA/MD Code,FIPS state code,FIPS county code,Census tract. Implied decimal point.,"Principal city flag. 0=not principal city, 1=principal city","Small county flag. T=tract record, S=small county, I=island area","Split tract flag. N=tract number occurs within one MA, S=split between Mas","Demographic data flag. X=Total persons/population or median family income is 0, D=total persons/population and median family income are not 0, I=Island Area","Urban/rural flag. U=urban, R=rural, M=mixed, I=Island Area",MSA/MD median family income,MSA/MD median household income,"Tract median family income as a percentage of the MSA/MD median family income. 2 decimal places, truncated.",FFIEC Estimated MSA/MD median family income,"Income indicator, which identifies low, moderate, middle, and upper income areas","CRA poverty criteria. 'X' - Yes , ' ' (blank space) - No","CRA unemployment criteria. 'X' - Yes , ' ' (blank space) - No","CRA distressed criteria. 'X' - Yes , ' ' (blank space) - No","CRA remote rural (low density) criteria. 'X' -Yes, ' ' (blank space) - No","Previous year CRA distressed criteria. 'X' - Yes , ' ' (blank space) - No","Previous year CRA underserved criterion. 'X' - Yes , ' ' (blank space) - No","Meets at least one of current or previous year's CRA distressed/underserved tract criteria? 'X' - Yes, ' ' (blank space) - No",Total persons,Total families,Total households,Total female population,Total male population,Total population minus non-Hispanic or latino White alone population,Minority population as percent of tract population rounded to two decimal places,Total population Hispanic and Non-Hispanic,Total population Hispanic only,Total population non-Hispanic,Total population non-Hispanic one race,Total population non-Hispanic White,Total population non-Hispanic Black/African American,Total population non-Hispanic American Indian or Alaska native,Total population non-Hispanic Asian,Total population non-Hispanic native Hawaiian or other Pacific Islander,Total population non-Hispanic some other race,Total population non-Hispanic two or more races,Total population non-Hispanic exactly two races,Total population non-Hispanic White and Black,Total population non-Hispanic White and American Indian or Alaska native,Total population non-Hispanic White and Asian,Total population non-Hispanic White and Native Hawaiian or other Pacific Islander,Total population non-Hispanic White and some other race,Total population non-Hispanic Black and American Indian or Alaska native,OMB civil rights non-Hispanic Black,OMB civil rights non-Hispanic American Indian or Alaska native,OMB civil rights non-Hispanic Asian,OMB civil rights Non-Hispanic native Hawaiian or other Pacific Islander,OMB civil rights non-Hispanic some other race,"OMB civil rights non-White, non-Hispanic two or more races",Total population Hispanic or Latino by race,Total population Hispanic or Latino and white,Total population Hispanic or Latino and Black/African-American,Total population Hispanic or Latino and American Indian or Alaska native,Total population Hispanic or Latino and Asian,Total population Hispanic or Latino and native Hawaiian or other Pacific Islander,Total population Hispanic or Latino and some other race,Total population Hispanic or Latino and two or more races,Total population by race,Total population one race,Total population White,Total population Black/African American,Total population American Indian or Alaska native,Total population Asian,Total population Native Hawaiian or other Pacific Islander,Total population some other race,Total population two or more races,Total population exactly two races,Total population White and Black,Total population White and American Indian or Alaska Native,Total population White and Asian,Total population White and Native Hawaiian or other Pacific Islander,Total population White and some other race,Total population Black and American Indian or Alaska Native,OMB civil rights Black,OMB civil rights American Indian or Alaska Native,OMB civil rights Asian,OMB civil rights Native Hawaiian or other Pacific Islander,OMB civil rights some other race,OMB civil rights two or more races,Total population urban and rural,Total population urban only,Total population inside urbanized area,Total population inside urban clusters,Total population rural only,Total population by household type,Total population in households,Total population in households by householder,Total population male householder,Male householder living alone,Male householder not living alone,Total population female householder,Female householder living alone,Female householder not living alone,Total population in households with opposite-sex spouse,Total population in households with same-sex spouse,Total population in households with opposite-sex unmarried partner,Total population in households with same-sex unmarried partner,Total population in households with child,Total population in households with biological child,Total population in households with adopted child,Total population in households with stepchild,Total population in households with grandchild,Total population in households with brother or sister,Total population in households with parent,Total population in households with parent-in-law,Total population in households with son-in-law or daughter-in-law,Total population in households with other relatives,Total population in households with foster child,Total population in households with other nonrelatives,Total population in group quarters,Total population 65 years and over,Total population 65 years and over in households,Total population 65 years and over in family households,Total population 65 years and over by householder,Total population 65 years and over with male householder,Total population 65 years and over with female householder,Total population 65 years and over living with spouse,Total population 65 years and over living with parent,Total population 65 years and over living with parent-in-law,Total population 65 years and over living with other relatives,Total population 65 years and over living with nonrelatives,Total population 65 years and over in nonfamily households,Total population 65 years and over in nonfamily household with male householder,Total male population 65 years and over in nonfamily household living alone,Total male population 65 years and over in nonfamily household not living alone,Total population 65 years and over in nonfamily household with female householder,Total female population 65 years and over in nonfamily household living alone,Total female population 65 years and over in nonfamily household not living alone,Total population 65 years and over in nonfamily household living with nonrelatives,Total population 65 years and over in group quarters,Total population by sex by age,Total male population,Total male population under 5 years,Total male population 5 to 9 years,Total male population 10 to 14 years,Total male population 15 to 17 years,Total male population 18 and 19 years,Total male population 20 years,Total male population 21 years,Total male population 22 to 24 years,Total male population 25 to 29 years,Total male population 30 to 34 years,Total male population 35 to 39 years,Total male population 40 to 44 years,Total male population 45 to 49 years,Total male population 50 to 54 years,Total male population 55 to 59 years,Total male population 60 and 61 years,Total male population 62 to 64 years,Total male population 65 and 66 years,Total male population 67 to 69 years,Total male population 70 to 74 years,Total male population 75 to 79 years,Total male population 80 to 84 years,Total male population 85 years and over,Male population under 15,Male population 15 to 17,Male population 18 to 24,Male population 25 to 39,Male population 40 to 49,Male population 50 to 61,Male population 62 and over,Male population 65 and over,Total female population,Total female population under 5 years,Total female population 5 to 9 years,Total female population 10 to 14 years,Total female population 15 to 17 years,Total female population 18 and 19 years,Total female population 20 years,Total female population 21 years,Total female population 22 to 24 years,Total female population 25 to 29 years,Total female population 30 to 34 years,Total female population 35 to 39 years,Total female population 40 to 44 years,Total female population 45 to 49 years,Total female population 50 to 54 years,Total female population 55 to 59 years,Total female population 60 and 61 years,Total female population 62 to 64 years,Total female population 65 and 66 years,Total female population 67 to 69 years,Total female population 70 to 74 years,Total female population 75 to 79 years,Total female population 80 to 84 years,Total female population 85 years and over,Female population under 15,Female population 15 to 17,Female population 18 to 24,Female population 25 to 39,Female population 40 to 49,Female population 50 to 61,Female population 62 and over,Female population 65 and over,Male and female population under 5 years,Male and female population 5 to 9 years,Male and female population 10 to 14 years,Male and female population 15 to 17 years,Male and female population 18 and 19 years,Male and female population 20 years,Male and female population 21 years,Male and female population 22 to 24 years,Male and female population 25 to 29 years,Male and female population 30 to 34 years,Male and female population 35 to 39 years,Male and female population 40 to 44 years,Male and female population 45 to 49 years,Male and female population 50 to 54 years,Male and female population 55 to 59 years,Male and female population 60 and 61 years,Male and female population 62 to 64 years,Male and female population 65 and 66 years,Male and female population 67 to 69 years,Male and female population 70 to 74 years,Male and female population 75 to 79 years,Male and female population 80 to 84 years,Male and female population 85 years and over,Male and female population under 15,Male and female population 15 to 17,Male and female population 18 to 24,Male and female population 25 to 39,Male and female population 40 to 49,Male and female population 50 to 61,Male and female population 62 and over,Male and female population 65 and over,Total male population under 16,Total female population under 16,Total male population 16 and 17,Total female population 16 and 17,Females median age,Males median age,Persons median age,Total population 5 yrs and over - age by language,Total population 5 to 17 yrs - age by language,Total 5-17 years that speak only English,Total 5-17 years that speak Spanish,Total 5-17 years that speak Spanish and English very well,Total 5-17 years that speak Spanish and English well,Total 5-17 years that speak Spanish and English not well,Total 5-17 years that speak Spanish and English not at all,Total 5-17 years that speak other Indo-European language,Total 5-17 years that speak Indo-European language and English very well,Total 5-17 years that speak Indo-European language and English well,Total 5-17 years that speak Indo-European language and English not well,Total 5-17 years that speak Indo-European language and English not at all,Total 5-17 years that speak Asian/Pacific Island language,Total 5-17 years that speak Asian/Pacific Island language and English very well,Total 5-17 years that speak Asian/Pacific Island language and English well,Total 5-17 years that speak Asian/Pacific Island language and English not well,Total 5-17 years that speak Asian/Pacific Island language and English not at all,Total 5-17 years that speak other languages,Total 5-17 years that speak other languages and English very well,Total 5-17 years that speak other languages and English well,Total 5-17 years that speak other languages and English not well,Total 5-17 years that speak other languages and English not at all,Total population 18-64 years - age by language,Total 18-64 years that speak only English,Total 18-64 years that speak Spanish,Total 18-64 years that speak Spanish and English very well,Total 18-64 years that speak Spanish and English well,Total 18-64 years that speak Spanish and English not well,Total 18-64 years that speak Spanish and English not at all,Total 18-64 years that speak other Indo-European language,Total 18-64 years that speak Indo-European language and English very well,Total 18-64 years that speak Indo-European language and English well,Total 18-64 years that speak Indo-European language and English not well,Total 18-64 years that speak Indo-European language and English not at all,Total 18-64 years that speak Asian/Pacific Island language,Total 18-64 years that speak Asian/Pacific Island language and English very well,Total 18-64 years that speak Asian/Pacific Island language and English well,Total 18-64 years that speak Asian/Pacific Island language and English not well,Total 18-64 years that speak Asian/Pacific Island language and English not at all,Total 18-64 years that speak other languages,Total 18-64 years that speak other languages and English very well,Total 18-64 years that speak other languages and English well,Total 18-64 years that speak other languages and English not well,Total 18-64 years that speak other languages and English not at all,Total 65 years and over - age by language,Total 65 years and over that speak only English,Total 65 years and over that speak Spanish,Total 65 years and over that speak Spanish and English very well,Total 65 years and over that speak Spanish and English well,Total 65 years and over that speak Spanish and English not well,Total 65 years and over that speak Spanish and English not at all,Total 65 years and over that speak other Indo-European language,Total 65 years and over that speak Indo-European language and English very well,Total 65 years and over that speak Indo-European language and English well,Total 65 years and over that speak Indo-European language and English not well,Total 65 years and over that speak Indo-European language and English not at all,Total 65 years and over that speak Asian/Pacific Island language,Total 65 years and over that speak Asian/Pacific Island language and English very well,Total 65 years and over that speak Asian/Pacific Island language and English well,Total 65 years and over that speak Asian/Pacific Island language and English not well,Total 65 years and over that speak Asian/Pacific Island language and English not at all,Total 65 years and over that speak other languages,Total 65 years and over that speak other languages and English very well,Total 65 years and over that speak other languages and English well,Total 65 years and over that speak other languages and English not well,Total 65 years and over that speak other languages and English not at all,Total population 25 years and over,Total male population 25 years and over,Total male population 25 years and over - no schooling,Total male population 25 years and over - nursery to 4th grade,Total male population 25 years and over - 5th and 6th grades,Total male population 25 years and over - 7th and 8th grades,Total male population 25 years and over - 9th grade,Total male population 25 years and over - 10th grade,Total male population 25 years and over - 11th grade,Total male population 25 years and over - 12th grade - no diploma,Total male high school graduate (includes equivalency),Total male population 25 years and over - some college - less than 1 year,Total male population 25 years and over - some college -1 or more years,Total male population 25 years and over - associate degree,Total male population 25 years and over - bachelor's degree,Total male population 25 years and over - master's degree,Total male population 25 years and over - professional degree,Total male population 25 years and over - doctorate degree,Total female population 25 years and over,Total female population 25 years and over - no schooling,Total female population 25 years and over - nursery to 4th grade,Total female population 25 years and over - 5th and 6th grades,Total female population 25 years and over - 7th and 8th grades,Total female population 25 years and over - 9th grade,Total female population 25 years and over - 10th grade,Total female population 25 years and over - 11th grade,Total female population 25 years and over - 12th grade - no diploma,Total female high school graduate (includes equivalency),Total female population 25 years and over - some college - less thn 1 year,Total female population 25 years and over - some college -1 or more years,Total female population 25 years and over - associate degree,Total female population 25 years and over - bachelor's degree,Total female population 25 years and over - master's degree,Total female population 25 years and over - professional degree,Total female population 25 years and over - doctorate degree,Total population in group quarters by major group quarters type,Total institutionalized population by major group quarters type,Total population in correctional facilities for adults,Total population in juvenile facilities,Total population in nursing facilities/skilled-nursing facilities,Total population in other institutional facilities,Total noninstitutionalized population by major group quarters type,Total population in college/university student housing,Total population in military quarters,Total population in other noninstitutionalized facilities,Total population 16 and over,Total male population 16 and over,Total male population 16 and over in labor force,Total male population 16 and over in Armed Forces,Total male population 16 and over - civilians,Total male population 16 and over - employed,Total male population 16 and over - unemployed,Total male population 16 and over not in labor force,Total female population 16 and over,Total female population 16 and over in labor force,Total female population 16 and over in Armed Forces,Total female population 16 and over - civilians,Total female population 16 and over - employed,Total female population 16 and over - unemployed,Total female population 16 and over not in labor force,Total number of households,"Total number of households < $10,000","Total number of households $10,000 to $14,999","Total number of households $15,000 to $19,999","Total number of households $20,000 to $24,999","Total number of households $25,000 to $29,999","Total number of households $30,000 to $34,999","Total number of households $35,000 to $39,999","Total number of households $40,000 to $44,999","Total number of households $45,000 to $49,999","Total number of households $50,000 to $59,999","Total number of households $60,000 to $74,999","Total number of households $75,000 to $99,999","Total number of households $100,000 to $124,999","Total number of households $125,000 to $149,999","Total number of households $150,000 to $199,999","Total number of households $200,000 or more",Median household income - tract level,Total number of White households,"Total number of White households < $10,000","Total number of White households $10,000 to $14,999","Total number of White households $15,000 to $19,999","Total number of White households $20,000 to $24,999","Total number of White households $25,000 to $29,999","Total number of White households $30,000 to $34,999","Total number of White households $35,000 to $39,999","Total number of White households $40,000 to $44,999","Total number of White households $45,000 to $49,999","Total number of White households $50,000 to $59,999","Total number of White households $60,000 to $74,999","Total number of White households $75,000 to $99,999","Total number of White households $100,000 to $124,999","Total number of White households $125,000 to $149,999","Total number of White households $150,000 to $199,999","Total number of White households $200,000 or more",Total number of Black or African American households,"Total number of Black households < $10,000","Total number of Black households $10,000 

In [82]:
census_2022['FIPS state code'].astype(str).str.pad(width=2, side='left', fillchar='0') + census_2022['FIPS county code'].astype(str).str.pad(width=3, side='left', fillchar='0') + census_2022['Census tract. Implied decimal point.'].astype(str).str.pad(width=6, side='left', fillchar='0')

0        01001020100
1        01001020200
2        01001020300
3        01001020400
4        01001020501
            ...
87270    78030960900
87271    78030961000
87272    78030961100
87273    78030961200
87274    78030990000
Length: 87275, dtype: object

In [92]:
hmda = download_csv_from_cloud_storage('temp_df', "2021_public_lar_pa.csv", 0)
print(f'census tract 1 unaltered: {hmda.census_tract[0]}')
print(f'census tract 1 cast as int: {hmda.census_tract[0].astype(int)}')
print(f'census tract 1 cast as np.int64: {hmda.census_tract[0].astype(np.int64)}')
hmda.census_tract = hmda.census_tract.fillna(0).astype(np.int64)
hmda = hmda[hmda['census_tract']!=0]
hmda['census_tract_merge'] = hmda.census_tract.astype(str).str.pad(width=3, side='left', fillchar='0')
hmda

It takes 0.3220040798187256 seconds to download 2021_public_lar_pa.csv

<ipython-input-92-4ac292945103>:1: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,44) have mixed types.Specify dtype option on import or set low_memory=False.
  hmda = download_csv_from_cloud_storage('temp_df', "2021_public_lar_pa.csv", 0)

census tract 1 unaltered: 42101030900.0
census tract 1 cast as int: -2147483648
census tract 1 cast as np.int64: 42101030900

,activity_year,lei,derived_msa_md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,combined_loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co_applicant_credit_score_type,applicant_ethnicity_1,applicant_ethnicity_2,applicant_ethnicity_3,applicant_ethnicity_4,applicant_ethnicity_5,co_applicant_ethnicity_1,co_applicant_ethnicity_2,co_applicant_ethnicity_3,co_applicant_ethnicity_4,co_applicant_ethnicity_5,applicant_ethnicity_observed,co_applicant_ethnicity_observed,applicant_race_1,applicant_race_2,applicant_race_3,applicant_race_4,applicant_race_5,co_applicant_race_1,co_applicant_race_2,co_applicant_race_3,co_applicant_race_4,co_applicant_race_5,applicant_race_observed,co_applicant_race_observed,applicant_sex,co_applicant_sex,applicant_sex_observed,co_applicant_sex_observed,applicant_age,co_applicant_age,applicant_age_above_62,co_applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus_1,aus_2,aus_3,aus_4,aus_5,denial_reason_1,denial_reason_2,denial_reason_3,denial_reason_4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units,census_tract_merge
0,2021,549300KDVJICP5T5BD05,37964,PA,42101.0,42101030900,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,3,0,2,1,31,1,2,2,2,145000,70.443,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,2,2,2,2,205000.0,1,1,3,5,1,NaN,37.0,20%-<30%,8,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,3,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,2,5,2,4,45-54,9999,No,NaN,1,1,6,NaN,NaN,NaN,NaN,9,4.0,NaN,NaN,4507,84.14,67500,69,646,1246,62,42101030900
1,2021,549300KDVJICP5T5BD05,33874,PA,42029.0,42029311700,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,4,0,2,1,1,2,2,1,2,105000,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,180.0,NaN,3.0,2,2,2,2,NaN,1,1,3,5,1,NaN,190.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,1,5,2,4,55-64,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,9662,37.73,116300,92,2406,3007,26,42029311700
2,2021,549300KDVJICP5T5BD05,37964,PA,42045.0,42045403300,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,4,2,2,2,2,35000,76.101,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,2,2,2,2,215000.0,1,1,3,5,1,NaN,136.0,>60%,8,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,3,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,1,5,2,4,25-34,9999,No,NaN,1,1,6,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,6658,32.37,67500,92,1409,2031,61,42045403300
3,2021,549300KDVJICP5T5BD05,10900,PA,42095.0,42095017800,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,2,2,2,1,2,35000,106.094,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,180.0,NaN,NaN,2,2,2,2,205000.0,1,1,3,5,1,NaN,90.0,20%-<30%,8,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,3,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,1,5,2,4,35-44,9999,No,NaN,1,1,6,NaN,NaN,NaN,NaN,9,4.0,NaN,NaN,2618,41.37,84900,85,637,1021,53,42095017800
4,2021,54930063XGNMIXS57091,37964,PA,42101.0,42101027100,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,3,0,2,1,32,2,2,1,2,35000,18.717,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,240.0,NaN,1.0,2,1,2,2,185000.0,1,1,3,5,1,NaN,76.0,<20%,9,2,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,1,3,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,1,1,1,2,1,1,55-64,65-74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,2938,96.36,67500,82,673,891,61,42101027100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38094,2021,549300CK7U1WMTIG6687,33874,PA,42091.0,42091204101,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,1,2,2,2,31,1,1,1,2,215000,NaN,2.175,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,405000,1,1,3,5,1,NaN,26.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,1,5,2,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3971,6.09,116300,92,1194,1831,76,42091204101
38095,2021,549300CK7U1WMTIG6687,33874,PA,42091.0,42091201902,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,71,2,2,31,1,1,1,2,215000,NaN,2.57,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,405000,1,1,3,5,1,NaN,60.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,2,5,2,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5708,24.89,116300,97,1850,1868,59,42091201902
38096,2021,549300CK7U1WMTIG6687,33874,PA,42091.0,42091208400,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Race Not Available,Joint,4,0,2,2,31,1,1,1,2,235000,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,NaN,1,1,3,5,1,NaN,0.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,2,6,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,2,2,1,2,2,2,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,3563,5.05,116300,85,1104,1269,24,42091208400
38097,2021,549300CK7U1WMTIG6687,33874,PA,42029.0,42029311300,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,1,71,2,2,31,1,1,1,2,335000,NaN,1.665,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,515000,1,1,3,5,1,NaN,27.0,NaN,9,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,2,4,1,5,2,4,>74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4762,23.46,116300,157,1017,1167,30,42029311300
38098,2021,549300CK7U1WMTIG6687,25420,PA,42099.0,42099030501,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Joint,1,71,2,2,31,1,1,1,2,235000,NaN,2.77,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,405000,1,1,3,5,1,NaN,34.0,NaN,9,9,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,3,3,5,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,3,3,2,1,3,3,>74,>74,Yes,Yes,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5238,5.88,84900,87,1868,2226,29,42099030501

In [93]:
### Merging
# Sample of Census Data Columns
sample_census = census_2022[census_2022['FIPS state code'] == 42]

cols_census = [
        'census_tract_merge', 
        'MSA/MD median family income', 
        'MSA/MD median household income',
        'Tract median family income as a percentage of the MSA/MD median family income. 2 decimal places, truncated.', 
        'FFIEC Estimated MSA/MD median family income',
        'Income indicator, which identifies low, moderate, middle, and upper income areas',
        '''CRA poverty criteria. 'X' - Yes , ' ' (blank space) - No''',
        '''CRA unemployment criteria. 'X' - Yes , ' ' (blank space) - No''',
        'Minority population as percent of tract population rounded to two decimal places',
        'Total population White', 
        'Total population Black/African American', 
        'Total population American Indian or Alaska native', 
        'Total population Asian', 
        'Total population Native Hawaiian or other Pacific Islander', 
        'Total population some other race', 
        'Total housing units', 
        'Total housing units - urban   ', 
        'Total housing units - rural', 
        'Total occupied housing units', 
        'Total vacant housing units'
        ]

cols_census_dict = {
        'census_tract_merge': 'census_tract_merge', 
        'MSA/MD median family income': 'msa_med_family_income', 
        'MSA/MD median household income': 'msa_med_household_income',
        'Tract median family income as a percentage of the MSA/MD median family income. 2 decimal places, truncated.': 'pct_tract_msa_med_fam_income', 
        'FFIEC Estimated MSA/MD median family income': 'ffiec_est_msa_med_fam_income',
        'Income indicator, which identifies low, moderate, middle, and upper income areas': 'income_category',
        '''CRA poverty criteria. 'X' - Yes , ' ' (blank space) - No''': 'cra_poverty',
        '''CRA unemployment criteria. 'X' - Yes , ' ' (blank space) - No''': 'cra_unemployment',
        'Minority population as percent of tract population rounded to two decimal places': 'minority_pct_of_tract',
        'Total population White': 'total_pop_white', 
        'Total population Black/African American': 'total_pop_black', 
        'Total population American Indian or Alaska native': 'total_pop_aioan', 
        'Total population Asian': 'total_pop_asian', 
        'Total population Native Hawaiian or other Pacific Islander': 'total_pop_nhopi', 
        'Total population some other race': 'total_pop_other', 
        'Total housing units': 'total_hus', 
        'Total housing units - urban   ': 'total_hus_urban', 
        'Total housing units - rural': 'total_hus_rural', 
        'Total occupied housing units': 'total_hus_occupied', 
        'Total vacant housing units': 'total_hus_vacant'
}
sample_census = census_2022[cols_census]
sample_census = sample_census.rename(columns=cols_census_dict)

# Sample of HMDA Cols

cols_hmda = [
        'census_tract_merge', 
        'lei',
        'derived_msa_md',
        'conforming_loan_limit',
        'derived_loan_product_type',
        'derived_dwelling_category',
        'derived_ethnicity',
        'derived_race',
        'derived_sex',
        'action_taken',
        'purchaser_type',
        'preapproval',
        'loan_type',
        'loan_purpose',
        'lien_status',
        'open_end_line_of_credit',
        'business_or_commercial_purpose',
        'loan_amount',
        'combined_loan_to_value_ratio',
        'interest_rate',
        'rate_spread',
        'hoepa_status',
        'total_loan_costs',
        'property_value',
        'income',
        'debt_to_income_ratio',
        'applicant_credit_score_type',
        'applicant_age'
]
sample_hmda = hmda[cols_hmda]

In [94]:
pd.set_option('display.max_columns', None)
sample_merge = sample_hmda.merge(sample_census, on = 'census_tract_merge', how='left')
sample_merge.head()

,census_tract_merge,lei,derived_msa_md,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,combined_loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,property_value,income,debt_to_income_ratio,applicant_credit_score_type,applicant_age,msa_med_family_income,msa_med_household_income,pct_tract_msa_med_fam_income,ffiec_est_msa_med_fam_income,income_category,cra_poverty,cra_unemployment,minority_pct_of_tract,total_pop_white,total_pop_black,total_pop_aioan,total_pop_asian,total_pop_nhopi,total_pop_other,total_hus,total_hus_urban,total_hus_rural,total_hus_occupied,total_hus_vacant
0,42101030900,549300KDVJICP5T5BD05,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,3,0,2,1,31,1,2,2,145000,70.443,NaN,NaN,3,NaN,205000.0,37.0,20%-<30%,8,45-54,68458.0,54520.0,72.62,75000.0,2.0,NaN,NaN,83.39,781.0,1686.0,1.0,644.0,0.0,590.0,1454.0,NaN,NaN,1405.0,49.0
1,42029311700,549300KDVJICP5T5BD05,33874,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,4,0,2,1,1,2,1,2,105000,NaN,NaN,NaN,3,NaN,NaN,190.0,NaN,9,55-64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42045403300,549300KDVJICP5T5BD05,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,4,2,2,2,35000,76.101,NaN,NaN,3,NaN,215000.0,136.0,>60%,8,25-34,68458.0,54520.0,99.68,75000.0,3.0,NaN,NaN,41.59,4084.0,1901.0,8.0,235.0,0.0,197.0,2854.0,NaN,NaN,2542.0,312.0
3,42095017800,549300KDVJICP5T5BD05,10900,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,2,2,1,2,35000,106.094,NaN,NaN,3,NaN,205000.0,90.0,20%-<30%,8,35-44,84676.0,69769.0,103.38,94300.0,3.0,NaN,NaN,53.98,1545.0,421.0,20.0,54.0,7.0,411.0,1231.0,NaN,NaN,1184.0,47.0
4,42101027100,54930063XGNMIXS57091,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,3,0,2,1,32,2,1,2,35000,18.717,NaN,NaN,3,NaN,185000.0,76.0,<20%,9,55-64,68458.0,54520.0,73.62,75000.0,2.0,NaN,NaN,96.01,113.0,1471.0,11.0,544.0,1.0,102.0,1001.0,NaN,NaN,968.0,33.0

In [111]:
sample_merge_clean = sample_merge[sample_merge.minority_pct_of_tract.notnull()]

def conditions(s):
    if (s['minority_pct_of_tract'] >= 50) and (s['pct_tract_msa_med_fam_income'] < 100):
        return 1
    else:
        return 0


sample_merge_clean['minority_census_tract'] = sample_merge_clean.apply(conditions, axis=1)

minority_tracts = sample_merge_clean[sample_merge_clean['minority_census_tract'] == 1]
minority_tracts.head()

<ipython-input-111-9b624582f730>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_merge_clean['minority_census_tract'] = sample_merge_clean.apply(conditions, axis=1)

,census_tract_merge,lei,derived_msa_md,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,combined_loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,property_value,income,debt_to_income_ratio,applicant_credit_score_type,applicant_age,msa_med_family_income,msa_med_household_income,pct_tract_msa_med_fam_income,ffiec_est_msa_med_fam_income,income_category,cra_poverty,cra_unemployment,minority_pct_of_tract,total_pop_white,total_pop_black,total_pop_aioan,total_pop_asian,total_pop_nhopi,total_pop_other,total_hus,total_hus_urban,total_hus_rural,total_hus_occupied,total_hus_vacant,minority_census_tract
0,42101030900,549300KDVJICP5T5BD05,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,3,0,2,1,31,1,2,2,145000,70.443,NaN,NaN,3,NaN,205000.0,37.0,20%-<30%,8,45-54,68458.0,54520.0,72.62,75000.0,2.0,NaN,NaN,83.39,781.0,1686.0,1.0,644.0,0.0,590.0,1454.0,NaN,NaN,1405.0,49.0,1
4,42101027100,54930063XGNMIXS57091,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,3,0,2,1,32,2,1,2,35000,18.717,NaN,NaN,3,NaN,185000.0,76.0,<20%,9,55-64,68458.0,54520.0,73.62,75000.0,2.0,NaN,NaN,96.01,113.0,1471.0,11.0,544.0,1.0,102.0,1001.0,NaN,NaN,968.0,33.0,1
9,42101034900,54930063XGNMIXS57091,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,5,0,2,1,32,1,2,2,225000,NaN,NaN,NaN,3,NaN,NaN,75.0,NaN,9,45-54,68458.0,54520.0,98.77,75000.0,3.0,NaN,NaN,53.94,2861.0,1398.0,24.0,435.0,2.0,500.0,2283.0,NaN,NaN,2030.0,253.0,1
11,42101028200,54930063XGNMIXS57091,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,2,2,2,1,35000,16.115,NaN,NaN,3,NaN,205000.0,48.0,20%-<30%,2,65-74,68458.0,54520.0,66.49,75000.0,2.0,NaN,NaN,96.64,187.0,3895.0,10.0,258.0,3.0,181.0,2260.0,NaN,NaN,2044.0,216.0,1
18,42101020300,54930063XGNMIXS57091,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,5,0,2,1,2,1,1,2,65000,NaN,NaN,NaN,3,NaN,NaN,82.0,NaN,9,65-74,68458.0,54520.0,61.45,75000.0,2.0,NaN,NaN,97.31,140.0,2188.0,11.0,19.0,0.0,238.0,1343.0,NaN,NaN,1094.0,249.0,1

In [118]:

sample_merge_clean = sample_merge[sample_merge.minority_pct_of_tract.notnull()]

def map_income(df):
    if df['income'] >= 0 and df['income'] <= 25:
        return '$0-$25k'
    elif df['income'] > 25 and df['income'] <= 50:
        return '$25k-$50k'
    elif df['income'] > 50 and df['income'] <= 100:
        return '$50k-$100k'
    elif df['income'] > 100 and df['income'] <= 150:
        return '$100k-$150k'
    elif df['income'] > 150 and df ['income'] <= 250:
        return '$150k-$250k'
    else:
        return '>$250k'

sample_merge_clean.income = sample_merge_clean.income.fillna(0)

sample_merge_clean['income_bin'] = sample_merge_clean.apply(map_income, axis=1)

def conditions(s):
    if (s['minority_pct_of_tract'] >= 50) and (s['pct_tract_msa_med_fam_income'] < 100):
        return 1
    else:
        return 0


sample_merge_clean['minority_census_tract'] = sample_merge_clean.apply(conditions, axis=1)

minority_tracts = sample_merge_clean[sample_merge_clean['minority_census_tract'] == 1]
minority_tracts.head()

C:\Miniconda\lib\site-packages\pandas\core\generic.py:5507: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
<ipython-input-118-cfc791a0f967>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_merge_clean['income_bin'] = sample_merge_clean.apply(map_income, axis=1)
<ipython-input-118-cfc791a0f967>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_merge_clean['minority_census_tract'] = sample_merge_clean.apply(conditions, axis=1)

,census_tract_merge,lei,derived_msa_md,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,combined_loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,property_value,income,debt_to_income_ratio,applicant_credit_score_type,applicant_age,msa_med_family_income,msa_med_household_income,pct_tract_msa_med_fam_income,ffiec_est_msa_med_fam_income,income_category,cra_poverty,cra_unemployment,minority_pct_of_tract,total_pop_white,total_pop_black,total_pop_aioan,total_pop_asian,total_pop_nhopi,total_pop_other,total_hus,total_hus_urban,total_hus_rural,total_hus_occupied,total_hus_vacant,income_bin,minority_census_tract
0,42101030900,549300KDVJICP5T5BD05,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,3,0,2,1,31,1,2,2,145000,70.443,NaN,NaN,3,NaN,205000.0,37.0,20%-<30%,8,45-54,68458.0,54520.0,72.62,75000.0,2.0,NaN,NaN,83.39,781.0,1686.0,1.0,644.0,0.0,590.0,1454.0,NaN,NaN,1405.0,49.0,$25k-$50k,1
4,42101027100,54930063XGNMIXS57091,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Joint,3,0,2,1,32,2,1,2,35000,18.717,NaN,NaN,3,NaN,185000.0,76.0,<20%,9,55-64,68458.0,54520.0,73.62,75000.0,2.0,NaN,NaN,96.01,113.0,1471.0,11.0,544.0,1.0,102.0,1001.0,NaN,NaN,968.0,33.0,$50k-$100k,1
9,42101034900,54930063XGNMIXS57091,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,5,0,2,1,32,1,2,2,225000,NaN,NaN,NaN,3,NaN,NaN,75.0,NaN,9,45-54,68458.0,54520.0,98.77,75000.0,3.0,NaN,NaN,53.94,2861.0,1398.0,24.0,435.0,2.0,500.0,2283.0,NaN,NaN,2030.0,253.0,$50k-$100k,1
11,42101028200,54930063XGNMIXS57091,37964,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Male,3,0,2,1,2,2,2,1,35000,16.115,NaN,NaN,3,NaN,205000.0,48.0,20%-<30%,2,65-74,68458.0,54520.0,66.49,75000.0,2.0,NaN,NaN,96.64,187.0,3895.0,10.0,258.0,3.0,181.0,2260.0,NaN,NaN,2044.0,216.0,$25k-$50k,1
18,42101020300,54930063XGNMIXS57091,37964,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,Black or African American,Female,5,0,2,1,2,1,1,2,65000,NaN,NaN,NaN,3,NaN,NaN,82.0,NaN,9,65-74,68458.0,54520.0,61.45,75000.0,2.0,NaN,NaN,97.31,140.0,2188.0,11.0,19.0,0.0,238.0,1343.0,NaN,NaN,1094.0,249.0,$50k-$100k,1

In [119]:
minority_tracts.interest_rate = minority_tracts.interest_rate.replace('Exempt', np.nan)
minority_tracts = minority_tracts[minority_tracts['interest_rate'].notnull()]
minority_tracts.interest_rate = minority_tracts.interest_rate.astype(np.float64)

minority_tracts.groupby(['census_tract_merge', 'income_bin']).mean().reset_index()

C:\Miniconda\lib\site-packages\pandas\core\generic.py:5507: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,census_tract_merge,income_bin,derived_msa_md,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,interest_rate,hoepa_status,income,applicant_credit_score_type,msa_med_family_income,msa_med_household_income,pct_tract_msa_med_fam_income,ffiec_est_msa_med_fam_income,income_category,minority_pct_of_tract,total_pop_white,total_pop_black,total_pop_aioan,total_pop_asian,total_pop_nhopi,total_pop_other,total_hus,total_hus_urban,total_hus_rural,total_hus_occupied,total_hus_vacant,minority_census_tract
0,42003030500,$0-$25k,38300.0,6.0,2.0,2.0,2.0,31.0,1.0,2.0,2.0,285000.0,2.2500,2.0,0.0,9.0,82642.0,61969.0,47.77,94800.0,1.0,76.52,728.0,1831.0,11.0,284.0,2.0,35.0,1865.0,NaN,NaN,1512.0,353.0,1.0
1,42003030500,$50k-$100k,38300.0,1.0,71.0,2.0,2.0,31.0,1.0,2.0,2.0,285000.0,2.2500,2.0,75.0,2.0,82642.0,61969.0,47.77,94800.0,1.0,76.52,728.0,1831.0,11.0,284.0,2.0,35.0,1865.0,NaN,NaN,1512.0,353.0,1.0
2,42003050100,$0-$25k,38300.0,6.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,115000.0,3.3750,2.0,0.0,9.0,82642.0,61969.0,45.67,94800.0,1.0,95.39,85.0,1604.0,0.0,5.0,0.0,13.0,989.0,NaN,NaN,848.0,141.0,1.0
3,42003050600,$50k-$100k,38300.0,1.0,6.0,2.0,1.0,31.0,1.0,2.0,2.0,195000.0,2.6250,2.0,64.0,3.0,82642.0,61969.0,74.33,94800.0,2.0,77.60,392.0,1142.0,12.0,72.0,0.0,27.0,1073.0,NaN,NaN,843.0,230.0,1.0
4,42003051000,$50k-$100k,38300.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,155000.0,3.3750,2.0,82.0,3.0,82642.0,61969.0,0.00,94800.0,0.0,73.40,472.0,1024.0,4.0,87.0,0.0,22.0,892.0,NaN,NaN,781.0,111.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,42101038200,$50k-$100k,37964.0,3.5,0.0,2.0,1.0,16.5,1.5,2.0,2.0,80000.0,5.0575,2.5,61.5,5.5,68458.0,54520.0,60.36,75000.0,2.0,52.59,1458.0,460.0,13.0,49.0,7.0,556.0,1269.0,NaN,NaN,1126.0,143.0,1.0
851,42133000300,$0-$25k,49620.0,1.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,95000.0,3.5000,2.0,21.0,3.0,82154.0,68940.0,34.36,93300.0,1.0,71.93,803.0,690.0,12.0,15.0,0.0,522.0,1227.0,NaN,NaN,1092.0,135.0,1.0
852,42133001100,$25k-$50k,49620.0,1.0,0.0,2.0,1.0,1.0,1.0,2.0,2.0,115000.0,3.2500,2.0,35.0,7.0,82154.0,68940.0,41.41,93300.0,1.0,78.40,1086.0,1148.0,40.0,18.0,9.0,993.0,1315.0,NaN,NaN,1124.0,191.0,1.0
853,42133001300,$25k-$50k,49620.0,1.0,1.0,2.0,1.0,31.0,1.0,2.0,2.0,75000.0,3.5000,2.0,44.0,1.0,82154.0,68940.0,83.35,93300.0,3.0,54.78,1666.0,684.0,11.0,29.0,2.0,501.0,1478.0,NaN,NaN,1396.0,82.0,1.0
854,42133001300,$50k-$100k,49620.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,105000.0,4.5000,3.0,73.0,3.0,82154.0,68940.0,83.35,93300.0,3.0,54.78,1666.0,684.0,11.0,29.0,2.0,501.0,1478.0,NaN,NaN,1396.0,82.0,1.0

# What do we want to show?

## 1. Comparison of total portfolio to PA Average

Bin income values and show average interest rate and debt-to-income ratio by the binned income

## 2. Tract by Tract comparison of total portfolio to PA Average

Same two statistics, but calculate difference from national mean for that tract, and show those values. Tracts with large differences should be flagged

## 3. Loan Portfolio by Size, Debt-to-Income Ratio, and Credit Score

Breakdown of Loan Portfolio, with comparatives to National Average.

## 4. Accepted Loans with "suspicious" income

Any large loans with low income, or extremely high debt to income ratio. Does interest rate match?

## 5. Denied Loans with suitable income

Any loans with high income, or extremely low debt to income ratio. Does interest rate match?

## 6. Loan Portfolio impact on Tract vacancy

Are any areas that have particularly high interest rates showing a similarly high rate of vacancy? Where is the most impacted area?

In [96]:
sample_hmda.interest_rate = sample_hmda.interest_rate.replace('Exempt', np.nan)
sample_hmda = sample_hmda[sample_hmda['interest_rate'].notnull()]
sample_hmda.interest_rate = sample_hmda.interest_rate.astype(np.float64)

sample_hmda.groupby(['census_tract_merge', 'lei']).mean().reset_index()

C:\Miniconda\lib\site-packages\pandas\core\generic.py:5507: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,census_tract_merge,lei,derived_msa_md,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,open_end_line_of_credit,business_or_commercial_purpose,loan_amount,interest_rate,hoepa_status,income,applicant_credit_score_type
0,42001030101,549300A6NF3MQMOHKJ20,23900.0,1.0,71.000000,2.0,1.0,31.0,1.0,2.0,2.0,155000.000000,2.250000,2.0,123.0,1.0
1,42001030101,549300BRJZYHYKT4BJ84,23900.0,1.0,3.000000,2.0,1.0,32.0,1.0,2.0,2.0,145000.000000,2.625000,2.0,100.0,3.0
2,42001030102,2549006IYID0ECYSJU25,23900.0,1.0,6.000000,2.0,1.0,1.0,1.0,2.0,2.0,195000.000000,3.125000,2.0,66.0,1.0
3,42001030102,549300A6NF3MQMOHKJ20,23900.0,1.0,71.000000,2.0,1.0,32.0,1.0,2.0,2.0,235000.000000,2.625000,2.0,102.0,3.0
4,42001030102,549300BRJZYHYKT4BJ84,23900.0,1.0,1.666667,2.0,1.0,31.0,1.0,2.0,2.0,258333.333333,2.871667,2.0,98.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,42133024001,549300BOXNV8VLRBDT24,49620.0,1.0,1.000000,2.0,1.0,32.0,1.0,2.0,2.0,185000.000000,2.375000,2.0,111.0,1.0
8773,42133024001,549300BRJZYHYKT4BJ84,49620.0,1.0,2.000000,2.0,3.0,1.0,1.0,2.0,2.0,245000.000000,2.375000,2.0,49.0,1.0
8774,42133024001,549300BX448ALT10FI43,49620.0,1.0,6.000000,2.0,3.0,32.0,1.0,2.0,2.0,315000.000000,2.750000,2.0,117.0,1.0
8775,42133024001,549300CLRXFVF83ZL806,49620.0,1.0,1.000000,2.0,1.0,31.0,1.0,2.0,2.0,205000.000000,2.625000,2.0,140.0,7.0
8776,42133024002,549300CLRXFVF83ZL806,49620.0,1.0,71.000000,2.0,2.0,1.0,1.0,2.0,2.0,315000.000000,3.750000,2.0,119.0,7.0

In [99]:
import pandas as pd
import folium 
from folium.plugins import StripePattern
import geopandas as gpd
import numpy as np

# We import the geoJSON file. 
url = ("https://raw.githubusercontent.com/python-visualization/folium/master/examples/data")
state_geo = f"{url}/us-states.json"

# We read the file and print it.
geoJSON_df = gpd.read_file(state_geo)
geoJSON_df.head()

   id        name                                           geometry
0  AL     Alabama  POLYGON ((-87.35930 35.00118, -85.60667 34.984...
1  AK      Alaska  MULTIPOLYGON (((-131.60202 55.11798, -131.5691...
2  AZ     Arizona  POLYGON ((-109.04250 37.00026, -109.04798 31.3...
3  AR    Arkansas  POLYGON ((-94.47384 36.50186, -90.15254 36.496...
4  CA  California  POLYGON ((-123.23326 42.00619, -122.37885 42.0...

In [ ]:
url = (
    "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data"
)
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"
state_data = pd.read_csv(state_unemployment)

bins = list(state_data["Unemployment"].quantile([0, 0.25, 0.5, 0.75, 1]))

m = folium.Map(location=[48, -102], zoom_start=5)

folium.Choropleth(
    geo_data=state_geo,
    data=state_data,
    columns=["State", "Unemployment"],
    key_on="feature.id",
    fill_color="BuPu",
    fill_opacity=0.7,
    line_opacity=0.5,
    legend_name="Unemployment Rate (%)",
    bins=bins,
    reset=True,
).add_to(m)

m

In [ ]:
# Center Map on State College, PA
center_point = [40.798214,-77.859909]
county_map = folium.Map(location=center_point, zoom_start=8)
display(county_map)

In [ ]:
def get_general_statistics(df):